name: SQL Server Automation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  automate-sql:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install SQL Client
      run: sudo apt-get install -y freetds-dev freetds-bin
      
    - name: Create Database and Table
      run: |
        sqlcmd -S 4.tcp.ngrok.io,12345 -U Auto_user -P StrongPassword123! -Q "CREATE DATABASE AutoTestDB;"
        sqlcmd -S 4.tcp.ngrok.io,12345 -U Auto_user -P StrongPassword123! -d AutoTestDB -Q "CREATE TABLE user (Name VARCHAR(50), Surname VARCHAR(50), Email VARCHAR(100));"
        sqlcmd -S 4.tcp.ngrok.io,12345 -U Auto_user -P StrongPassword123! -d AutoTestDB -Q "CREATE PROCEDURE InsertUser @Name VARCHAR(50), @Surname VARCHAR(50), @Email VARCHAR(100) AS BEGIN INSERT INTO user (Name, Surname, Email) VALUES (@Name, @Surname, @Email); END;"
        sqlcmd -S 4.tcp.ngrok.io,12345 -U Auto_user -P StrongPassword123! -d AutoTestDB -Q "EXEC InsertUser @Name='GitHub', @Surname='Action', @Email='github.action@example.com';"
