name: Deploy SQL Jobs to MS SQL Server

on:
  push:
    branches: [ main ]  # Runs when changes are pushed to main branch
    paths:
      - 'HandsOnProjects/Timesheet/sql scripts/DeployAllJobs.sql'  # Only trigger if this file changes

jobs:
  deploy-sql-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy SQL Jobs
        run: |
          # Install SQLCMD (if not already available)
          sudo apt-get update && sudo apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

          # Execute the SQL script
          sqlcmd -S "${{ secrets.TIMESHEETDB_SQL_SERVER_PUBLIC_URL }}" \
                 -U "${{ secrets.TIMESHEETDB_SQL_USER }}" \
                 -P "${{ secrets.TIMESHEETDB_SQL_PASSWORD }}" \
                 -i "HandsOnProjects/Timesheet/sql scripts/DeployAllJobs.sql"
