name: Deployment Exercise 1
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install
        working-directory: "DevOpps/GithubActions/01+Starting+Project (10)/01 Starting Project"
      
      - name: Lint
        run: npm run test
        working-directory: "DevOpps/GithubActions/01+Starting+Project (10)/01 Starting Project"

  deploy:
    runs-on: ubuntu-latest
    needs: lint  # Ensures linting runs before deployment
    steps:
      - name: Get code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install
        working-directory: "DevOpps/GithubActions/01+Starting+Project (10)/01 Starting Project"
      
      - name: Lint
        run: npm run test
        working-directory: "DevOpps/GithubActions/01+Starting+Project (10)/01 Starting Project"
      
      - name: Build code
        run: npm run build
        working-directory: "DevOpps/GithubActions/01+Starting+Project (10)/01 Starting Project"
      
      - name: Deploy code
        run: echo "Deploying..."
