name: Deploy SQL Agent Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Added to enable manual triggering

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install sqlcmd
        run: |
          Invoke-WebRequest -Uri "https://aka.ms/download-sqlcmd" -OutFile "sqlcmd.zip"
          Expand-Archive -Path sqlcmd.zip -DestinationPath "C:\sqlcmd"
          echo "C:\sqlcmd" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Deploy All SQL Agent Jobs
        env:
          SQL_SERVER: ${{ secrets.TIMESHEETDB_SQL_SERVER_PUBLIC_URL }}
          SQL_USER: ${{ secrets.TIMESHEETDB_SQL_USER }}
          SQL_PASSWORD: ${{ secrets.TIMESHEETDB_SQL_PASSWORD }}
        run: |
          sqlcmd -S "$env:SQL_SERVER" -U "$env:SQL_USER" -P "$env:SQL_PASSWORD" -d msdb -i "HandsOnProjects/Timesheet/sql scripts/DeployAllJobs.sql"
