name: Deploy SQL Jobs to MS SQL Server

on:
  push:
    branches: [ main ]
    paths:
      - 'HandsOnProjects/Timesheet/sql scripts/DeployAllJobs.sql'

jobs:
  deploy-sql-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SQL Tools
        uses: microsoft/setup-sqlcmd@v1  # Official Microsoft action

      - name: Deploy SQL Jobs
        run: |
          sqlcmd -S "${{ secrets.TIMESHEETDB_SQL_SERVER_PUBLIC_URL }}" \
                 -U "${{ secrets.TIMESHEETDB_SQL_USER }}" \
                 -P "${{ secrets.TIMESHEETDB_SQL_PASSWORD }}" \
                 -i "HandsOnProjects/Timesheet/sql scripts/DeployAllJobs.sql"
