name: Show Runner Identity
 
on:
  workflow_dispatch:
 
jobs:
  show-identity:
    runs-on: self-hosted
 
    steps:
      - name: Print Windows user (whoami)
        shell: powershell
        run: |
          Write-Output "Current runner is executing as:"
          whoami
